# Generated by Django 5.1.4 on 2025-01-15 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dialoghistory",
            options={"verbose_name_plural": "Dialog histories"},
        ),
    ]
