# Generated by Django 5.1.4 on 2025-01-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0002_alter_dialoghistory_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dialoghistory",
            name="content",
        ),
        migrations.RemoveField(
            model_name="dialoghistory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="dialoghistory",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="dialoghistory",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
