# Generated by Django 5.1.5 on 2025-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_remove_dialoghistory_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialoghistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
